### ISSUE TITLE
can the lib can use to raspberry pi3  ?

### ISSUE THREAD

**Issue by tommy840803** [bitcraze/libdw1000#14]
Hi ,
I have a pi , the libdw1000 can use on the pi3 ?
The library is so wonderful !

**Comment by ataffanel** [comment]
Hi,
as far as I know it has never been tried, but yes this lib should work on a Raspberry pi. All you have to do is implement the required low level functions to access the DW1000 chip: https://github.com/bitcraze/libdw1000#ops.

There is nothing in the lib that should prevent it to work on a Linux system, and if you find anything that does not work it is most likely a bug and you are welcome to make a ticket or a PR about it.
