### ISSUE TITLE
Sending data through UWB

### ISSUE THREAD

**Issue by afnan** [bitcraze/libdw1000#15]
Hi,

Using this code can you send custom data (other than position) using UWB from tag to the listener?

**Comment by ataffanel** [comment]
Yes, this code actually do not contain any code related to position or ranging: the DW1000 chip is a radio chip able to send/receive data packet and to measure very accurately the TX and RX timestamp.

So this code can only send custom data, if your happen to send data related to timing/position you can also implement ranging/positioning algorithm.

**Comment by afnan** [comment]
Correct me if I am wrong

1. This code will replace the DWM1001 firmware?
2. We can still use decawave library and their Location Engine ?
