### ISSUE TITLE
the difference between this lib and official dw1000 API

### ISSUE THREAD

**Issue by dusz7** [bitcraze/libdw1000#17]
Sorry to open an issue to ask this question.
Recently I work on a project about indoor-location using DW1000, like your LOCO system (https://github.com/bitcraze/lps-node-firmware).
And i wonder why didn't you use the official DW1000 API (https://www.decawave.com/software/) but rewrite this driver by yourself?
Is it because you want to use several DW1000 radios at the same time?
Thank you

**Comment by ataffanel** [comment]
The main reason for re-writing (ie. porting from the Arduino driver) the driver was mostly because of the license: the Crazyflie 2.0 firmware is licensed under GPLV3 and my understanding is that the license of the Decawave code was not compatible with it.
