### ISSUE TITLE
Unable to Communicate via SPI with Flow Deck also attached

### ISSUE THREAD

**Issue by brianwu568** [bitcraze/libdw1000#23]
Hello, I am experiencing issues in which the DW1000 is not able to properly communicate via the SPI bus when a flow deck and AI deck are attached at the same time.

In the past, I have had the flow deck and the DW1000 in the loco positioning deck work together seamlessly when those were the only decks attached. I have modified the AI deck to work with the DW1000 by disabling the GPIO1 pin from its deck driver object, but when I attach all three of these decks together on the same drone, I get an error that the DW1000 is not able to initialize properly,. Upon further investigation, it seems that the DW1000 is not communicating properly via SPI.

I am perplexed as to why this is the case because each of these 3 chips should have different GPIO pins as chip selects. From my understanding, the current configuration is that the flow deck CS is on GPIO3, the loco deck CS is on GPIO1, and the AI deck CS is on GPIO4. What could be causing the conflict that prevents SPI from initializing properly for the DW1000 in the loco, but works perfectly for the flow deck?

**Comment by knmcguire** [comment]
Hi! I think it is better to keep communicating through your open discussion thread until we find the proper culprit for this. Then if we find out there is indeed a bug here, we will open an issue. Just to make communication easier

https://github.com/orgs/bitcraze/discussions/854
