### ISSUE TITLE
tag send data with 850Kbps to anchor with 6.8Mbps, anchor can receive right data

### ISSUE THREAD

**Issue by justinleeyang** [bitcraze/libdw1000#9]
tag send data with 850Kbps to anchor with 6.8Mbps, anchor can receive right data.

maybe the libdw1000 issue ?

**Comment by ataffanel** [comment]
This is not a problem of the lib, this is a characteristic of the DW1000: the datarate setting is transmited as part of the PHR part of the packet. So there is a TX bitrate setting but there is no RX bitrate setting, only an RX bitrate report to inform the receiver at which bitrate the packet was transmitted.
